### ISSUE TITLE
OPERACIONES CON SISTEMAS NUMERICOS

### ISSUE THREAD

**Issue by JordanMendoza401** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-JordanMendoza401#1]
[Jordan Mendoza Aparicio. Operaciones de Sistemas.pdf](https://github.com/user-attachments/files/16859328/Jordan.Mendoza.Aparicio.Operaciones.de.Sistemas.pdf)

**Comment by Yesus-12** [comment]
Portada:24/25
Procedimiento:25/25
Figuras ilustraciones y fotografías :25/25
Resultados y conclusiones:24/25
Calificacion final:19.6

**Comment by josealfredo79** [comment]
bien hecho y revisado..
